const blankValues = {
  player: null,
  sport: null,
  team: null,
  year: null,
  manufacturer: null,
  product: null,
  brand: null,
  setOrInsert: null,
  cardNumber: null,
  rookieStatus: null,
  parallel: null,
  serialNumber: null,
  autograph: null,
  memorabilia: null,
  imageVariation: null,
};

export const embeddedCatalogRecords = [
  {
    id: "2026-topps-series-2-cn-14-nolan-ryan-green-foil",
    label: "2026 Topps Series 2 Crooked Numbers Nolan Ryan #CN-14 - Green Foil /99",
    sourceUrl: "https://www.beckett.com/news/2026-topps-series-2-baseball-cards/",
    aliases: ["nolan ryan", "california angels", "angels", "topps"],
    visibleMarks: ["75 years of baseball"],
    visualCues: ["green", "foil", "reflective", "crooked", "stylized angels"],
    values: {
      ...blankValues,
      player: "Nolan Ryan",
      sport: "Baseball",
      team: "California Angels",
      year: "2026",
      manufacturer: "Topps",
      product: "Topps Series 2",
      brand: "Topps",
      setOrInsert: "Crooked Numbers",
      cardNumber: "CN-14",
      rookieStatus: false,
      parallel: "Green Foil /99",
      autograph: false,
      memorabilia: false,
      imageVariation: false,
    },
  },
  {
    id: "2026-topps-series-1-173-nolan-ryan-golden-mirror-legend",
    label: "2026 Topps Series 1 Nolan Ryan #173 - Golden Mirror Legend Variation",
    sourceUrl: "https://www.beckett.com/news/2026-topps-series-1-baseball-variations-guide-and-image-gallery/",
    aliases: ["nolan ryan", "california angels", "angels", "topps"],
    visibleMarks: ["75 years of baseball"],
    visualCues: ["golden mirror", "legend variation", "image variation"],
    values: {
      ...blankValues,
      player: "Nolan Ryan",
      sport: "Baseball",
      team: "California Angels",
      year: "2026",
      manufacturer: "Topps",
      product: "Topps Series 1",
      brand: "Topps",
      setOrInsert: "Golden Mirror Legend Variation",
      cardNumber: "173",
      rookieStatus: false,
      autograph: false,
      memorabilia: false,
      imageVariation: true,
    },
  },
];
